---
- name: Wait for linux host to be available
  ansible.builtin.wait_for_connection:
    delay: "{{ infra_generic_wait_for_linux_hosts_delay }}"
    sleep: "{{ infra_generic_wait_for_linux_hosts_sleep }}"
    timeout: "{{ infra_generic_wait_for_linux_hosts_timeout }}"
    connect_timeout: "{{ infra_generic_wait_for_linux_hosts_connect_timeout }}"
  register: r_wait
  ignore_errors: true

- name: Ping hosts
  ansible.builtin.ping:
  register: r_ping
  retries: "{{ infra_generic_wait_for_linux_hosts_retries }}"
  delay: "{{ infra_generic_wait_for_linux_hosts_delay }}"
  until: r_ping is succeeded
