---
- name: Destroy Open Environment Cloudformation stack
  amazon.aws.cloudformation:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    stack_name: "{{ project_tag }}-open-environment"
    state: absent
    region: "{{ aws_region_loop | default(aws_region) | default(region) | default('us-east-1') }}"
