---
- name: Test describe-instances
  community.aws.ec2_instance_facts:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: us-east-1
    filters:
      "tag:foo": bar
  register: r_access
  failed_when: false

- name: Exit if cannot list instances using the credentials
  when: '"error" in r_access'
  ansible.builtin.fail:
    msg: "user.info: Cannot list instances using the provided credentials"
