---
- name: Import pre-checks
  ansible.builtin.import_tasks: pre_checks.yml

- name: Iterate over all instances and create DNS entries
  when: >-
    _instance.public_dns | default(false) or
    _instance.floating_ip | default(false)
  ansible.builtin.include_tasks: instance_loop.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: _instance
