---
- name: Set facts for Windows remote access
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ infra_windows_connection_facts[infra_windows_connection_facts_type] | dict2items }}"
