---
######################### Prep hosts to run OpenShift Installer

- name: Step 004.1 - Host preparation for OpenShift 4 deployment
  hosts: bastions
  become: true
  gather_facts: false
  tasks:
  - name: Call Role to provision OCP4 install host
    ansible.builtin.include_role:
      name: host_ocp4_provisioner

######################### Run OpenShift Installer

- name: Step 004.2 - Install OpenShift
  hosts: bastions
  gather_facts: false
  become: false
  tasks:
  - name: Call Role to install OpenShift
    when: install_ocp4 | default(true) | bool
    ansible.builtin.include_role:
      name: host_ocp4_installer
