---
- name: Create the base directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.gcp"
    mode: "0700"
    owner: "{{ ansible_user }}"
    state: directory

- name: Define service account creds file
  ansible.builtin.set_fact:
    svc_account_creds_file: "{{ output_dir }}/svc-acct-creds.json"

- name: Create key file for Google Cloud SDK
  ansible.builtin.copy:
    src: "{{ svc_account_creds_file }}"
    dest: "/home/{{ ansible_user }}/.gcp/osServiceAccount.json"
    mode: "0600"
    owner: "{{ ansible_user }}"
  become: false
