---
- name: Include SSH tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Update all packages and reboot VMs
  when: update_packages | bool
  block:
  - name: Update all packages
    ansible.builtin.package:
      name: '*'
      state: latest
      nobest: true
    register: r_package
    retries: 3
    until: r_package is succeeded
    async: 3600
    poll: 30

  - name: Determine if reboot is needed
    ansible.builtin.command: needs-restarting -r
    register: r_needs_restarting
    failed_when: false
    changed_when: false

  - name: Reboot all VMs after updating to the latest release
    when: r_needs_restarting.rc == 1
    block:
    - name: Reboot all VMs
      ansible.builtin.reboot:
        msg: "RHEL updates installing. Rebooting now."
        reboot_timeout: 300
        connect_timeout: 300
        pre_reboot_delay: 10
        post_reboot_delay: 30
      ignore_unreachable: true
      register: r_reboot
    rescue:
    - name: Debug reboot
      ansible.builtin.debug:
        msg: "{{ r_reboot }}"

    - name: Recover from UNREACHABLE if any
      ansible.builtin.meta: clear_host_errors

    - name: Reboot the VMs again if the first attempt has failed
      ansible.builtin.reboot:
        msg: "RHEL updates installing. Rebooting now."
        reboot_timeout: 300
        connect_timeout: 300
        pre_reboot_delay: 10
        post_reboot_delay: 30
      when: r_reboot is not succeeded

    always:
    - name: Update network facts after reboot
      ansible.builtin.setup:
        gather_subset:
        - 'network'
        - 'virtual'

######################## Install Basic Packages
- name: Run setup if gather_facts hasn't been run
  when: ansible_distribution_major_version is not defined
  ansible.builtin.setup:
    gather_subset: min

- name: Install common packages for RHEL 9
  when: ansible_distribution_major_version == "9"
  ansible.builtin.import_tasks: packages_el9.yml

- name: Install extra packages
  when: common_extra_packages | default([]) | length > 0
  ansible.builtin.import_tasks: packages_extra.yml

######################## Update Specific Packages if defined
- name: Update specific Packages and Reboot VMs
  when:
  - update_specific_packages is defined
  - update_specific_packages | length > 0
  block:
  - name: Update specified packages
    ansible.builtin.package:
      name: "{{ update_specific_packages }}"
      state: latest
    register: r_package
    retries: 3
    until: r_package is succeeded
    async: 3600
    poll: 30

  - name: Determine if reboot is needed
    ansible.builtin.command:
      cmd: needs-restarting -r
    register: r_needs_restarting
    failed_when: false
    changed_when: false

  - name: Reboot VMs if necessary
    when: r_needs_restarting.rc == 1
    block:
    - name: Reboot VMs
      ansible.builtin.reboot:
        reboot_timeout: 300
        connect_timeout: 300
        msg: "Updates installed. Rebooting now."
        pre_reboot_delay: 60
        post_reboot_delay: 10

    - name: Refresh network facts post-reboot
      ansible.builtin.setup:
        gather_subset:
        - 'network'
        - 'virtual'
