---
- name: Ensure mandatory variables are set
  when: item not in vars or vars[item] == ''
  ansible.builtin.fail:
    msg: "Variable {{ item }} is not defined"
  loop:
  - guid
  - config
  - pool_region
  - pool_manager_aws_access_key_id
  - pool_manager_aws_secret_access_key
  - pool_manager_vault_password

- name: Ensure email and student name are defined
  when:
  - email is undefined
  - student_name is undefined
  ansible.builtin.fail:
    msg: "email and student_name are both undefined."
