---
- name: Include tasks
  when: infra_images_instances | default([]) | length > 0
  vars:
    findme:
    - "{{ cloud_provider }}.yaml"
    - notsupported.yaml
  ansible.builtin.include_tasks: "{{ lookup('first_found', findme) }}"
