---
- name: Check for API certificate and restart cert manager if necessary
  block:
  - name: Wait until API Certificate is ready
    when: not _ocp4_workload_cert_manager_api_cert_ready | default(false) | bool
    kubernetes.core.k8s_info:
      api_version: cert-manager.io/v1
      kind: Certificate
      name: cert-manager-api-cert
      namespace: openshift-api
      wait: true
      wait_sleep: 5
      wait_timeout: 800
      wait_condition:
        type: "Ready"
        status: "True"
    register: r_certificate_api

  - name: Mark certificate ready
    when: not r_certificate_api is failed
    ansible.builtin.set_fact:
      _ocp4_workload_cert_manager_api_cert_ready: true

  rescue:
  - name: Restart cert-manager on failure
    kubernetes.core.k8s:
      api_version: v1
      kind: Pod
      state: absent
      label_selectors:
      - app.kubernetes.io/instance=cert-manager
      - app.kubernetes.io/component=controller
      namespace: cert-manager

  - name: Set retry count
    ansible.builtin.set_fact:
      _ocp4_workload_cert_manager_api_retry_count: "{{ _ocp4_workload_cert_manager_api_retry_count | int + 1 }}"

  - name: Report fail on api certificate failure
    when:
    - (_ocp4_workload_cert_manager_api_retry_count | int > ocp4_workload_cert_manager_api_cert_max_retries | int)
    - r_certificate_api is failed
    block:
    - name: Print error message if requesting certificates failed
      when: ocp4_workload_cert_manager_ignore_errors | bool
      ansible.builtin.debug:
        msg: "Requesting certificate for API servers failed after {{ ocp4_workload_cert_manager_api_cert_max_retries }} retries."

    - name: Fail if requesting certificates failed
      when: not ocp4_workload_cert_manager_ignore_errors | bool
      ansible.builtin.fail:
        msg: "Requesting certificate for API servers failed after {{ ocp4_workload_cert_manager_api_cert_max_retries }} retries."
