---
update_packages: true

common_install_basic_packages_retries: 10

# Common Packages to install for RHEL 9
common_packages_el9:
- python3
- unzip
- bash-completion
- tmux
- bind-utils
- wget
- nano
- git
- vim-enhanced
- httpd-tools
- openldap-clients
- podman
- skopeo
- buildah
- tree
- jq
- libffi-devel

# Extra packages to install in addition to common packages
common_extra_packages: []
