---
- name: Import AWS Pre checks
  ansible.builtin.import_playbook: aws_pre_checks.yml

- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Run infra-images
    ansible.builtin.include_role:
      name: infra-images

  - name: Run infra-aws-capacity-reservation
    vars:
      ACTION: provision
    ansible.builtin.include_role:
      name: infra-aws-capacity-reservation

  - name: Rerun detection
    when: agnosticd_aws_capacity_reservation_results.reservations | default({}) | length > 0
    block:
    - name: Empty the agnosticd_images and run the detection again
      ansible.builtin.set_fact:
        agnosticd_images: {}

    - name: Run infra-images again to use the proper region selected by the reservations
      ansible.builtin.include_role:
        name: infra-images

  - name: Run infra-aws-open-environment Role
    when: agnosticd_open_environment | default(false) | bool
    vars:
      ACTION: provision
    ansible.builtin.include_role:
      name: infra-aws-open-environment

  - name: Create SSH provision key
    when:
    - instances | default([]) | length
    - ssh_provision_key_name is undefined
    ansible.builtin.include_role:
      name: create_ssh_provision_key

  - name: Locate environment SSH key
    when: instances | default([]) | length > 0
    ansible.builtin.include_role:
      name: locate_env_authorized_key

  - name: Create keypair in AWS
    when: instances | default([]) | length > 0
    ansible.builtin.include_role:
      name: infra-aws-ssh-key

  - name: Run infra-aws-template-generate Role
    ansible.builtin.include_role:
      name: infra-aws-template-generate

  - name: Run infra-aws-template-create Role
    when: cloudformation_enabled | default(true) | bool
    vars:
      aws_region_loop: "{{ aws_region }}"
    ansible.builtin.include_role:
      name: infra-aws-template-create

  - name: Run infra-aws-template-create Role into FallBack region
    when:
    - cloudformation_enabled | default(true) | bool
    - fallback_regions is defined
    - cloudformation_out is failed
    vars:
      aws_region_loop: "{{ item }}"
    ansible.builtin.include_role:
      name: infra-aws-template-create
    loop: "{{ fallback_regions }}"

  - name: Report Cloudformation error
    ansible.builtin.fail:
      msg: "FAIL {{ project_tag }} Create Cloudformation"
    when:
    - cloudformation_enabled | default(true) | bool
    - not cloudformation_out is succeeded

- name: Step 001.2 Create inventory and SSH config setup
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Create SSH config
    when: create_ssh_config | default(true) | bool
    block:
    # Sometimes the infra step is skipped, for example when scaling up a cluster.
    # when step001.1 is skipped, aws_region_final is not defined.
    - name: Include detect region tasks
      when: aws_region_final is not defined
      ansible.builtin.include_tasks: aws_detect_region_tasks.yml

    - name: Run infra-aws-create-inventory role
      ansible.builtin.include_role:
        name: infra-aws-create-inventory

    - name: Run common SSH config generator role
      when:
      - groups.bastions is defined
      - groups.bastions | length > 0
      ansible.builtin.include_role:
        name: infra-common-ssh-config-generate

- name: Include global vars again, this time for all hosts now that the inventory is built
  ansible.builtin.import_playbook: ../include_vars.yml

- name: Step 001.3 Configure Linux hosts and wait for connection
  hosts:
  - all:!windows:!network
  gather_facts: false
  any_errors_fatal: true
  ignore_errors: false
  become: true
  tasks:
  - name: Set facts for remote access
    ansible.builtin.set_fact:
      aws_region_final: "{{ hostvars['localhost'].aws_region_final }}"
      ansible_ssh_extra_args: "{{ ansible_ssh_extra_args | default() }} -F {{ output_dir }}/{{ env_type }}_{{ guid }}_ssh_conf"

  - name: Run infra-aws-wait_for_linux_hosts role
    ansible.builtin.include_role:
      name: infra-aws-wait_for_linux_hosts

  - name: Run infra-aws-linux-set-hostname role
    ansible.builtin.include_role:
      name: infra-aws-linux-set-hostname

  - name: Add authorized_keys
    when: >-
      ssh_authorized_keys | default([]) | length > 0
      or
      all_ssh_authorized_keys | default([]) | length > 0
    ansible.builtin.include_role:
      name: ssh_authorized_keys

- name: Step 001.4 Configure Windows hosts and wait for connection
  gather_facts: false
  hosts:
  - windows
  tasks:
  - name: Set facts for Windows remote access
    when: infra_windows_connection_facts_type is defined
    ansible.builtin.include_role:
      name: infra-windows-connection-facts

  - name: Set facts for remote access
    when: infra_windows_connection_facts_type is not defined
    ansible.builtin.set_fact:
      ansible_become: false
      ansible_connection: winrm
      ansible_host: "{{ public_dns_name }}"
      ansible_password: "{{ hostvars['localhost'].windows_password | default(hostvars['localhost'].generated_windows_password) }}"
      ansible_port: 5986
      ansible_user: Administrator
      ansible_winrm_server_cert_validation: ignore
      aws_region_final: "{{ hostvars['localhost'].aws_region_final }}"

  - name: Run infra-aws-wait_for_linux_hosts role
    ansible.builtin.include_role:
      name: infra-aws-wait_for_windows_hosts

  - name: Set output_dir for all Windows hosts
    ansible.builtin.set_fact:
      output_dir: "{{ hostvars.localhost.output_dir }}"
