---
- name: Step 001.0 Infrastructure Pre-Checks
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Test aws command
    ansible.builtin.shell: command -v aws
    failed_when: false
    changed_when: false
    check_mode: false
    register: r_aws

  - name: Fail if AWS command CLI if not available
    when: r_aws.rc != 0
    ansible.builtin.fail:
      msg: AWS command not found in PATH.
