---
# The output_dir holds all of the files generated during the deployment
# This includes generated Heat templates, SSH config, SSH keys
# This must be an absolute path and no vars (like $HOME or ~)
output_dir: /tmp/output_dir

# The {{ guid }} is used everywhere and it is what differentiates otherwise
# identical environments. Make this unique. Usually they are 4 characters, but
# it can be any reasonable length.
guid: notset

# The name of the OpenShift cluster that will be deployed.
# This is primarily used if you want to automate the OpenShift deployment.
cluster_name: "cluster-{{ guid }}"

# Used to add metadata (tags) to OpenStack objects created
project_tag: "{{ config }}-{{ guid }}"

# Why is this config being deployed? Override for specific environments
# Some valid: development, ilt, production, event
purpose: development

# Enable this if you want to create a user on the bastion
# Mutually exclusive with {{ install_ipa_client }}
install_student_user: true

# This should be overwritten based on the user ordering the catalog item
# It will be used by the bastion-student-user role and created on the bastion
student_name: lab-user

# Run the bastion role
install_bastion: true

# FTL is used for grading and solving. It will pull in the external ftl-injector role.
# This might be enabled when we have solvers to run or graders for ILT
# When enabled a requirements.yml must exist in the config to specify the ftl-injector role and tag.
install_ftl: false

# Only satellite is supported for RHEL 9 and newer
repo_method: satellite

# These vars are needed and nee to come from secrets:
# satellite_url: # This should be stored in secrets
# satellite_org: # This should be stored in secrets
# satellite_activationkey: # This should be stored in secrets

# -------------------------------------------------
# Role: common
# -------------------------------------------------
# Packages to install on all of the hosts deployed as part of the agnosticd config
# This invokes the "common" role
install_common: true

# To install extra packages (beyond what's in the common list of packages)
# common_extra_packages:
# - java-17-openjdk
# - maven

# As part of the "common" role, this cause it to do a yum update on the host
update_packages: true

# How to deploy OpenShift
# Valid values are
# - openshift_install
# - openshift_assisted
# - openshift_hcp_cnv
host_ocp4_deploy_installation_method: openshift_install

# Types of Nodes (workers / masters) are set in the
# cloud specific vars file
# Number of Nodes
master_instance_count: 3
worker_instance_count: 2

# Types and Sizes of Disks for nodes
# Only set if you know what you're doing...
# master_storage_type: "__DEFAULT__"
# master_storage_size: "30Gi"
# worker_storage_type: "__DEFAULT__"
# worker_storage_size: "100Gi"

# Use 4.17 for latest available release in the `stable-4.17` directory.
# Use 4.17.1 for exactly the specified release
host_ocp4_installer_version: "4.17"

# See role host-ocp4-installer for additional OpenShift 4 Installer options
# E.g. OpenShift Cluster processor architectore or OpenShift installer download location

# Pull secret needs to be defined in secrets
# Get from https://try.openshift.com
# ocp4_pull_secret: ''

# Should be set from secrets or cloud config
ocp4_base_domain: example.opentlc.com

# Red Hat Network Plugins for OpenShift:
# - OVNKubernetes
#
# Third Party Network Plugins for OpenShift
# - Calico (tested on OCP 4.7)
#
host_ocp4_installer_network_type: OVNKubernetes

# Set to true to enable creating a cluster-admin service account during installation
openshift_cluster_admin_service_account_enable: false

# Print user info
ocp4_cluster_show_access_user_info: true
openshift_cluster_show_access_user_info: true

# YAML List of Infrastructure Workloads.
# REQUIRES Ansible 2.7+ on the deployer host
# Empty by default - to be set by specific configurations
workloads: []

# Suggested workloads for a base workshop cluster:
#  - ocp4_workload_cert_manager
#  - ocp4_workload_authentication

# Some workloads create infrastructure that needs to be removed
# when deleting the software or infrastructure. These workloads run on the controller
remove_workloads: []
