---
- name: Step 005 - Post software
  hosts: bastions
  become: false
  gather_facts: false
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeconfig
  tasks:
  - name: Print post software
    ansible.builtin.debug:
      msg: "Post-Software Steps starting"

  - name: Setup cluster-admin service account
    when: openshift_cluster_admin_service_account_enable | bool
    ansible.builtin.include_role:
      name: openshift_cluster_admin_service_account

  - name: Remove AWS Credentials from bastion
    when: cloud_provider == 'aws'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.aws/credentials"
      state: absent

  - name: Remove Azure Credentials directory from bastion
    when: cloud_provider == 'azure'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.azure"
      state: absent

  - name: Remove the openshift-installer GCP Credentials directory from bastion
    when: cloud_provider == 'gcp'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.gcp"
      state: absent

  - name: Remove gcloud CLI Credentials directory from bastion
    when: cloud_provider == 'gcp'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.config/gcloud"
      state: absent

- name: Step 005.2 - Deploy Workloads
  ansible.builtin.import_playbook: workloads.yml

- name: Step 005.5 Print Student Info
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Report Access Information
    when:
    - install_student_user | bool
    - openshift_cluster_show_access_user_info | bool
    - cloud_provider != "openshift_cnv"
    vars:
      _bastion_inventory_name: "{{ groups['bastions'][0] }}"
      _bastion_ssh_password: "{{ hostvars[bastion_hostname]['student_password'] }}"
      _kubeadmin_password: "{{ hostvars[bastion_hostname]['kubeadmin_password']['content'] | b64decode }}"
    block:
    - name: Set Bastion Hostname (AWS)
      when: cloud_provider == 'aws'
      ansible.builtin.set_fact:
        _bastion_public_hostname: "{{ hostvars[_bastion_inventory_name].shortname }}.{{ guid }}{{ subdomain_base_suffix }}"

    - name: Set Bastion Hostname (GCP)
      when: cloud_provider == "azure" or cloud_provider == "gcp"
      ansible.builtin.set_fact:
        _bastion_public_hostname: "bastion.{{ guid }}.{{ ocp4_base_domain }}."

    - name: Set Bastion Hostname (Other)
      when: _bastion_public_hostname is not defined
      ansible.builtin.set_fact:
        _bastion_public_hostname: "{{ hostvars[_bastion_inventory_name].shortname }}.{{ guid }}.{{ ocp4_base_domain }}"

    - name: Print GCP access user info
      when:
      - cloud_provider == "gcp"
      - agnosticd_open_environment | default(false) | bool
      ansible.builtin.include_role:
        name: open-env-gcp-user-info

    - name: Print access user info
      agnosticd_user_info:
        data:
          bastion_public_hostname: "{{ _bastion_public_hostname }}"
          bastion_ssh_password: "{{ _bastion_ssh_password }}"
          bastion_ssh_user_name: "{{ student_name }}"
        msg: |
          You can access your bastion via SSH using password '{{ _bastion_ssh_password }}':
          ssh {{ student_name }}@{{ _bastion_public_hostname }}

  - name: Print access user info (CNV)
    when:
    - install_student_user | bool
    - cloud_provider == "openshift_cnv"
    agnosticd_user_info:
      data:
        bastion_ssh_port: "{{ hostvars[groups['bastions'][0]].bastion_ssh_port }}"
      msg: |
        You can access your bastion via SSH using password '{{ hostvars[groups['bastions'][0]]['student_password'] }}':
        ssh {{ student_name }}@{{ openshift_cnv_ssh_address }} -p {{ hostvars[groups['bastions'][0]].bastion_ssh_port }}

# - name: Step 005.5 Clean up Google SDK
#   hosts: localhost
#   gather_facts: false
#   become: false
#   tasks:
#   - name: Remove Google Cloud SDK
#     when: cloud_provider == "gcp"
#     ansible.builtin.file:
#       path: "{{ output_dir }}/google-cloud-sdk"
#       state: absent
