---
- name: Step 004 - Software
  hosts: bastions
  gather_facts: false
  become: true
  tasks:
  - name: Debug openshift-cluster software playbook
    ansible.builtin.debug:
      msg: "openshift-cluster Software playbook"
