---
# Workloads are being run on bastion.
# This enables using the k8s module in the workload.
# openshift python module is installed for Python3
- name: Install workloads
  hosts: localhost
  # hosts: bastions
  gather_facts: false
  # run_once: true
  become: false
  environment:
    KUBECONFIG: "{{ hostvars.localhost.output_dir }}/{{ config }}_{{ guid }}_kubeconfig"
  tasks:
  # - name: Set Ansible Python interpreter to k8s virtualenv
  #   ansible.builtin.set_fact:
  #     ansible_python_interpreter: /opt/virtualenvs/k8s/bin/python

  - name: Install workloads
    when: workloads | default([]) | length > 0
    ansible.builtin.include_role:
      name: "{{ workload_loop_var }}"
    vars:
      ACTION: "provision"
    loop: "{{ workloads }}"
    loop_control:
      loop_var: workload_loop_var
