---
- name: Copy IAM template to output_dir
  ansible.builtin.copy:
    dest: "{{ output_dir }}/CF-IAM.json"
    src: files/CF-IAM.json
    mode: "0664"

- name: Create IAM role using Cloudformation
  amazon.aws.cloudformation:
    profile: "{{ account_profile }}"
    template: "{{ output_dir }}/CF-IAM.json"
    region: "{{ aws_region }}"
    stack_name: roles
  register: r_cfiamrole
  until: r_cfiamrole is succeeded
  delay: 60
  retries: 5
