---
- name: Setup krb5.conf file
  ansible.builtin.copy:
    dest: "{{ output_dir }}/krb5.conf"
    content: |
      [libdefaults]
      default_realm = {{ kerberos_realm }}
      dns_lookup_realm = true
      dns_lookup_kdc = true
      rdns = false
      dns_canonicalize_hostname = false
      ticket_lifetime = 24h
      forwardable = true
      udp_preference_limit = 0
      default_ccache_name = KEYRING:persistent:%{uid}
    mode: "0660"

- name: Delete records
  environment:
    KRB5CCNAME: /tmp/krb_cache_{{ account_name }}
    KRB5_CONFIG: "{{ output_dir }}/krb5.conf"
  when: nuke_sandbox | bool
  block:
  - name: Login kerberos
    when: kerberos_keytab is defined
    ansible.builtin.command: >-
      kinit -kt "{{ kerberos_keytab }}" {{ kerberos_user }}

  - name: Login kerberos using password
    when: kerberos_password is defined
    ansible.builtin.command: >-
      kinit {{ kerberos_user }}
    args:
      stdin: "{{ kerberos_password }}"

  - name: Fetch all NS records for this sandbox
    ansible.builtin.shell: >-
      host -t ns -W 60 -R 10 {{ account_name }}.{{ ipa_domain }}
      | awk '{ print $4 }'
      | perl -pe 's/\.$//'
    register: r_recordfind

  - name: Save ipa_ns_records
    ansible.builtin.set_fact:
      ipa_ns_records: "{{ r_recordfind.stdout.split('\n') }}"

  - name: Delete all NS records that are not needed anymore
    when: _z != ''
    ansible.builtin.command: >-
      ipa dnsrecord-del {{ ipa_domain }}. {{ account_name }} --ns-rec={{ _z }}.
    loop: "{{ ipa_ns_records | difference(ns_records) }}"
    loop_control:
      loop_var: _z

  - name: Add NS records to IPA
    when: >-
      ipa_ns_records | length == 0
      or ipa_ns_records | difference(ns_records) | length != 0
      or  ns_records | difference(ipa_ns_records) | length != 0
    ansible.builtin.command: >-
      ipa dnsrecord-add {{ ipa_domain }}. {{ account_name }} --ns-rec={{ _z }}.
    loop: "{{ ns_records }}"
    loop_control:
      loop_var: _z
    register: r_ipacommand
    failed_when:
    - r_ipacommand.rc != 0
    - '"ERROR: no modifications to be performed" not in r_ipacommand.stderr'
    changed_when: >-
      "ERROR: no modifications to be performed"
      not in r_ipacommand.stderr

  always:
  - name: Destroy kerberos ticket
    ansible.builtin.command: kdestroy
