---
- name: Create output_dir
  ansible.builtin.file:
    path: "{{ output_dir }}"
    state: directory

- ansible.builtin.include_tasks: test_ipa.yml
  tags: ipa
  when:
    - kerberos_user is defined
    - kerberos_password is defined or kerberos_keytab is defined
