---
- name: Check subscription-manager package existence
  when: cloud_provider == 'gcp' or cloud_provider == 'azure'
  ansible.builtin.command: which subscription-manager
  ignore_errors: true
  register: check_sm_out

- name: Install subscription-manager package
  when:
  - cloud_provider == 'gcp' or cloud_provider == 'azure'
  - check_sm_out is failed
  ansible.builtin.package:
    name: subscription-manager
    state: present

- name: Remove rh-amazon-rhui-client package
  when: cloud_provider == 'aws'
  ansible.builtin.package:
    name: rh-amazon-rhui-client
    state: absent
    disablerepo: "*"    ## This option is undocumented but works, Pulls from yum & dnf

- name: Unregister the system just in case
  ansible.builtin.include_tasks: unregister.yml

- name: Install CA certificate from satellite server
  ansible.builtin.get_url:
    url: "https://{{ set_repositories_satellite_hostname }}/pub/katello-server-ca.crt"
    dest: /etc/pki/ca-trust/source/anchors/{{ set_repositories_satellite_hostname }}.ca.crt
    mode: u=rw,go=r
    validate_certs: false
  retries: 10
  delay: 10

- name:  Update CA Trust Bundle 
  ansible.builtin.command: update-ca-trust

- name: Remove satellite Cert
  ansible.builtin.package:
    name: katello-ca-consumer-*.noarch
    state: absent
    disablerepo: "*"
  ignore_errors: true

- name: Find current repository files
  ansible.builtin.find:
    paths: /etc/yum.repos.d
    recurse: false
    patterns:
    - '*.repo'
  register: r_find_repos

- name: Remove current repository files
  ansible.builtin.file:
    path: "{{ file.path }}"
    state: absent
  loop: "{{ r_find_repos.files }}"
  loop_control:
    loop_var: file
    label: "{{ file.path }}"
  ignore_errors: true

# WK: use `yum` to allow ignore of GPG errors
#     `package` does not have that options and results in random failures
- name: Install Satellite CA certificate package
  ansible.builtin.yum:
    name: "{{ set_repositories_satellite_ca_rpm_url }}"
    state: present
    disablerepo: "*"
    disable_gpg_check: true
  register: r_install_satellite_ca_rpm
  until: not r_install_satellite_ca_rpm.failed
  retries: 10
  delay: 10

# prutledg - package profile reporting is slamming the satellite server and not necessary
- name: Disable Reporting Of Package Profile to Satellite
  community.general.ini_file:
    path: /etc/rhsm/rhsm.conf
    section: rhsm
    option: report_package_profile
    value: "0"
    mode: "0664"

- name: Run setup if gather_facts hasn't been run
  when: ansible_date_time is not defined
  ansible.builtin.setup:
    gather_subset: min

- name: Generate UUID for dmi.system.uuid if cloud provider is Equinix Metal
  when: cloud_provider == 'equinix_metal'
  ansible.builtin.set_fact:
    dmi_system_uuid: "{{ 999999999 | random | to_uuid }}"

- name: Set set_repositories_subscription_hostname with randomization
  when: set_repositories_subscription_hostname is not defined
  ansible.builtin.set_fact:
    set_repositories_subscription_hostname: >-
      {%- if guid in inventory_hostname -%}
      {{ inventory_hostname }}-{{ ansible_date_time.iso8601_basic | lower }}
      {%- else -%}
      {{ inventory_hostname }}.{{ guid }}.internal-{{ ansible_date_time.iso8601_basic | lower }}
      {%- endif -%}

- name: Set network.fqdn in /etc/rhsm/facts/katello.facts
  ansible.builtin.copy:
    dest: /etc/rhsm/facts/katello.facts
    content: "{{ __content | to_json }}"
    mode: "0664"
  vars:
    __content: >-
      {{
        {"network.fqdn": set_repositories_subscription_hostname}
        | combine({"dmi.system.uuid": dmi_system_uuid} if cloud_provider == 'equinix_metal' else {})
      }}

- name: Register with activation-key
  when: set_repositories_satellite_ha is not defined or not set_repositories_satellite_ha | bool
  community.general.redhat_subscription:
    state: present
    consumer_name: "{{ set_repositories_subscription_hostname }}"
    server_hostname: "{{ set_repositories_satellite_hostname }}"
    activationkey: "{{ set_repositories_satellite_activationkey }}"
    org_id: "{{ set_repositories_satellite_org | default(satellite_org) }}"
    pool: "{{ set_repositories_satellite_pool | default(omit) }}"

- name: Register with activation-key with HA
  when: set_repositories_satellite_ha is defined and set_repositories_satellite_ha | bool
  community.general.redhat_subscription:
    state: present
    consumer_name: "{{ set_repositories_subscription_hostname }}"
    server_hostname: "{{ set_repositories_satellite_hostname }}"
    server_port: "8443"
    server_prefix: /rhsm
    rhsm_baseurl: "https://{{ set_repositories_satellite_hostname }}/pulp/repos"
    activationkey: "{{ set_repositories_satellite_activationkey }}"
    org_id: "{{ set_repositories_satellite_org | default(satellite_org) }}"
    pool: "{{ set_repositories_satellite_pool | default(omit) }}"
    force_register: "{{ set_repositories_force_register | default('false') }}"

- name: Enable RHSM to manage repositories
  ansible.builtin.command: subscription-manager config --rhsm.manage_repos=1

- name: Lock RHEL 9 release to specific version
  when: set_repositories_rhel9_lock_release is defined and ansible_os_family == 'RedHat' and ansible_distribution_major_version == "9"
  ansible.builtin.command: subscription-manager release --set={{ set_repositories_rhel9_lock_release }}
  register: lock_result
  until: lock_result is succeeded
  retries: 15
  delay: 10

- name: Enable repos
  community.general.rhsm_repository:
    name: "*"
    state: enabled
  when:
  - set_repositories_use_content_view | bool
  - set_repositories_satellite_activationkey != ''

# Remove all repos when using rhel_repos
# This will resolve any dependency issues with unwanted repositories still being enabled
- name: Purge existing repos
  community.general.rhsm_repository:
    name: '*'
    purge: true
  when:
  - not set_repositories_use_content_view | bool
  - rhel_repos is defined

- name: Enable repos for RHEL
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop:
  - '{{ rhel_repos }}'
  when:
  - not set_repositories_use_content_view | bool
  - rhel_repos is defined

# This would be used to skip registering with Satellite,
# but still be able to access the repos via certificate auth.
# This will only run if you have satellite_key and satellite_cert defined,
# but not set_repositories_satellite_activationkey
- name: Set up repos to access Satellite using cert
  when:
  - satellite_key is defined
  - satellite_cert is defined
  block:
  - name: Create the certificate and key files
    ansible.builtin.file:
      state: touch
      path: "{{ item }}"
      mode: "0660"
    loop:
    - "/etc/pki/tls/Red_GPTE.key"
    - "/etc/pki/tls/Red_GPTE.pem"

  - name: Add certificate and key content
    ansible.builtin.copy:
      dest: "{{ item.file }}"
      content: "{{ item.contents }}"
      mode: "0660"
    loop:
    - {file: "/etc/pki/tls/Red_GPTE.key", contents: "{{ satellite_key }}"}
    - {file: "/etc/pki/tls/Red_GPTE.pem", contents: "{{ satellite_cert }}"}

  - name: Create open.repo template on host
    ansible.builtin.template:
      src: "./files/repos_template.j2"
      dest: /etc/yum.repos.d/open_{{ config }}.repo
      mode: "0664"

- name: Clean repositories
  ansible.builtin.command: "yum clean all"
