---
- name: Check if template exists for the environment
  ansible.builtin.stat:
    path: "../configs/{{ config }}/files/cloud_providers/{{ cloud_provider }}_cloud_template.j2"
  register: stat_local_template

- name: Use CloudFormation template from the environment
  when: stat_local_template.stat.exists
  ansible.builtin.set_fact:
    cloudformation_template_src: "../configs/{{ config }}/files/cloud_providers/{{ cloud_provider }}_cloud_template.j2"

- name: Use the default CloudFormation template
  when: not stat_local_template.stat.exists
  ansible.builtin.set_fact:
    cloudformation_template_src: "templates/cloud_template.j2"

- name: Print cloudformation_template_src
  ansible.builtin.debug:
    var: cloudformation_template_src
