---
- name: Copy Template to S3
  amazon.aws.aws_s3:
    bucket: "{{ bucket_templates }}"
    object: "{{ config }}.{{ guid }}.{{ cloud_provider }}_cloud_template"
    src: "{{ cloudformation_template }}"
    mode: put
...
