---
- name: Search for instances in region {{ loop_region }}
  community.aws.ec2_instance_facts:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ loop_region }}"
  register: r_instances

- name: Set length
  ansible.builtin.set_fact:
    _ri_len: "{{ r_instances.instances | rejectattr('state.name', 'equalto', 'terminated') | list | length }}"

- name: Fail when no instances found
  when: _ri_len | int > 0
  ansible.builtin.fail:
    msg: "user.info: {{ _ri_len }} instances found in region {{ loop_region }} AWS account."
