---
- name: Save output dir
  block:
  - name: Create output_dir archive
    ansible.builtin.include_tasks:
      file: create_output_dir_archive.yml

  - name: Upload output_dir archive to S3
    when: agnosticd_save_output_dir_s3_bucket is defined
    amazon.aws.s3_object:
      aws_access_key: "{{ agnosticd_save_output_dir_s3_access_key_id }}"
      aws_secret_key: "{{ agnosticd_save_output_dir_s3_secret_access_key }}"
      mode: put
      ignore_nonexistent_bucket: true
      src: >-
        {{ agnosticd_save_output_dir_archive_tempfile -}}
        {{- '.gpg' if agnosticd_save_output_dir_archive_password is defined else '' -}}
      region: "{{ agnosticd_save_output_dir_s3_region }}"
      bucket: "{{ agnosticd_save_output_dir_s3_bucket }}"
      object: >-
        {{ agnosticd_save_output_dir_archive }}
        {{- '.gpg' if agnosticd_save_output_dir_archive_password is defined else '' -}}
      overwrite: always
      tags: "{{ cloud_tags_final }}"

  always:
  - name: Remove output_dir archive tempfile
    when: agnosticd_save_output_dir_archive_tempfile is defined
    ansible.builtin.file:
      path: "{{ agnosticd_save_output_dir_archive_tempfile }}"
      state: absent

  - name: Remove output_dir encrypted archive tempfile
    when: agnosticd_save_output_dir_archive_password is defined
    ansible.builtin.file:
      path: "{{ agnosticd_save_output_dir_archive_tempfile }}.gpg"
      state: absent
...
