---
# Run the installation. This should be true but can be overridden to skip the install to debug
# post installation tasks.
host_ocp4_installer_install_openshift: true

# To enable FIPS mode on an OpenShift 4 cluster
host_ocp4_installer_fips_enable: false

# Multi architecture support. The default is to use an x86_64 Linux
# bastion to install an x86_64 Linux cluster.
# Other combinations are x86_64 Linux bastion to install an arm64 Linux Cluster

# OpenShift Architecture to use for the installed cluster.
# Default: x86_64
# Other options: arm64
host_ocp4_installer_architecture_cluster: x86_64

# Where to download the OpenShift installer and client binaries from
# Only used if the host_ocp4_installer_url and host_ocp4_client_url are not defined
# Official Mirror
# host_ocp4_installer_root_url: >-
#   {{ 'https://mirror.openshift.com/pub/openshift-v4/aarch64/clients' if ocp4_architecture_cluster | default('x86_64') is match('arm64')
#   else 'https://mirror.openshift.com/pub/openshift-v4/clients'
#   }}

# Network Type:
# Valid values:
# - OVNKubernetes
# - Calico
host_ocp4_installer_network_type: OVNKubernetes

# CloudFront Mirror
host_ocp4_installer_root_url: >-
  {{ 'http://d3s3zqyaz8cp2d.cloudfront.net/pub/openshift-v4/aarch64/clients' if ocp4_architecture_cluster is match('arm64')
  else 'http://mirror.openshift.com/pub/openshift-v4/clients'
  }}

# Use 4.17 for latest available release in the `stable-4.17` directory.
# Use 4.17.1 for exactly the specified release
host_ocp4_installer_version: 4.17

# Install an OpenShift 4 Developer Preview Release
# Specify the direct link to the OpenShift installer and the OpenShift client
# When URLs are specified the host_ocp4_installer_root_url is being ignored
# Set the installer version for other dependencies to know which version is being used
#
# host_ocp4_installer_use_dev_preview: true
# host_ocp4_installer_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/candidate-4.18/openshift-install-linux.tar.gz
# host_ocp4_client_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/candidate-4.18/openshift-client-linux.tar.gz

# Controls for agnosticd_user_info
host_ocp4_installer_set_user_data: true
host_ocp4_installer_show_user_info: true

# Set user data for kubedamin password.
# Usually the kubeadmin is disabled so this must be explicitly enabled.
host_ocp4_installer_set_user_data_kubeadmin_password: false

# When master_storage_type == io1 or io2,
# calculate the IOPS:
# IOPS = 2000 << number of worker * 100 << 32000
# ex: 10 workers == 2000 iops
#     20 workers == 2000 iops
#     30 workers == 3000 iops
#     40 workers == 4000 iops
# See OpenShift documentation: https://docs.openshift.com/container-platform/4.6/installing/installing_aws/installing-aws-customizations.html
# And AWS documentation: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html
host_ocp4_installer_master_storage_iops: >-
  {{ [
  2000,
  [32000, worker_instance_count | default(2) | int * 100 ] | min
  ] | max | int
  }}
