---
- name: Ensure mandatory variables are set
  when: item not in vars or vars[item] == ''
  ansible.builtin.fail:
    msg: "!!!!!!!! Variable {{ item }} is not defined !!!!!!!!!"
  loop:
  - pool_manager_aws_access_key_id
  - pool_manager_aws_secret_access_key
  - pool_manager_vault_password
  - sandbox_name
  - nuke_sandbox
  - ipa_user

- name: Fail when ipa variables are undefined
  when:
  - ipa_password is undefined
  - ipa_keytab_base64 is undefined
  ansible.builtin.fail:
    msg: Please define at least ipa_password or ipa_keytab_base64

- name: Fail when too many variables are defined
  when:
  - ipa_password is defined
  - ipa_keytab_base64 is defined
  ansible.builtin.fail:
    msg: Please define  ipa_password OR ipa_keytab_base64, not both.

- name: Create output_dir
  ansible.builtin.file:
    path: "{{ output_dir }}"
    state: directory
    mode: "0775"
