---
- name: Run infra-aws-sandbox
  when: ipa_password is defined
  vars:
    account_name: "{{ sandbox_name }}"
    account_email: "{{ sandbox_email }}"
    account_destination_ou: "{{ sandbox_organization_unit }}"
    dynamodb_region: "{{ pool_region }}"
    dynamodb_table: "{{ pool_table }}"
    aws_master_profile: "{{ pool_manager_profile }}"
    kerberos_user: "{{ ipa_user }}"
    kerberos_password: "{{ ipa_password }}"
    output_dir: "{{ playbook_dir | default('/tmp') }}/output_dir"
    operation: RESET
  ansible.builtin.include_role:
    name: infra-aws-sandbox

- name: Ipa_keytab_base64 defined
  when: ipa_keytab_base64 is defined
  block:
  - name: Write down the keytab file based on the base64 version
    ansible.builtin.copy:
      dest: "{{ ipa_keytab_file }}"
      content: "{{ ipa_keytab_base64 | b64decode }}"
      mode: "0664"

  - name: Run infra-aws-sandbox
    vars:
      account_name: "{{ sandbox_name }}"
      account_email: "{{ sandbox_email }}"
      account_destination_ou: "{{ sandbox_organization_unit }}"
      dynamodb_region: "{{ pool_region }}"
      dynamodb_table: "{{ pool_table }}"
      aws_master_profile: "{{ pool_manager_profile }}"
      kerberos_user: "{{ ipa_user }}"
      kerberos_keytab: "{{ ipa_keytab_file }}"
      output_dir: "{{ playbook_dir | default('/tmp') }}/output_dir"
      operation: RESET
    ansible.builtin.include_role:
      name: infra-aws-sandbox

  always:
  - name: Delete keytab file
    ansible.builtin.file:
      path: "{{ ipa_keytab_file }}"
      state: absent
