---
- name: Set Alias name to account
  when: not account_altready_exists
  ansible.builtin.command: >-
    aws --profile {{ account_name }}
    iam create-account-alias --account-alias {{ account_name }}{{ alias_suffix }}
  register: _createaccountalias
  failed_when:
  - _createaccountalias.rc != 0
  - '"already exists" not in _createaccountalias.stderr'
  changed_when: '"already exists" not in _createaccountalias.stderr'
