---
- name: Get all records
  ansible.builtin.command: >-
    aws --profile {{ account_name }}
    route53 list-resource-record-sets --hosted-zone-id {{ _hostedzoneid }}
  register: r_records

- name: Set records to delete
  ansible.builtin.set_fact:
    change_batch_dest: "{{ output_dir }}/{{ account_name }}_{{ _hostedzoneid }}_delete_records.json"
    records_to_delete: >-
      {{ r_records.stdout |from_json
      | json_query('ResourceRecordSets')
      | rejectattr('Name', 'equalto', aws_public_zone)
      | list
      }}

- name: Delete records
  when: records_to_delete|length > 0
  block:
  - name: Create route53 change batch (JSON)
    ansible.builtin.copy:
      dest: "{{ change_batch_dest }}"
      content: |
        {
          "Comment": "Delete all records for {{ _hostedzoneid }}",
          "Changes": [
          {% for record in records_to_delete %}
          {   "Action": "DELETE",
              "ResourceRecordSet": {{ record | to_json }}
          }{{ "," if not loop.last else "" }}
          {% endfor %}
          ]
        }
      mode: "0664"

  - name: Delete all record from the zone
    ansible.builtin.command: >-
      aws --profile {{ account_name }}
      route53 change-resource-record-sets
      --hosted-zone-id={{ _hostedzoneid }}
      --change-batch=file://{{ change_batch_dest }}
