---
- name: Import pre-checks
  ansible.builtin.import_tasks: pre_checks.yml

- name: Import vault
  ansible.builtin.import_tasks: vault.yml

- name: Import account
  ansible.builtin.import_tasks: account.yml

- name: Import profile
  ansible.builtin.import_tasks: profile.yml

- name: Import iam
  ansible.builtin.import_tasks: iam.yml

- name: Import alias
  ansible.builtin.import_tasks: alias.yml

- name: Include ou
  when:
  - account_destination_ou is defined
  - operation == 'CREATE'
  ansible.builtin.include_tasks: ou.yml

- name: Include regions
  ansible.builtin.include_tasks: regions.yml

- name: Include reset
  when: operation == 'RESET'
  ansible.builtin.include_tasks: reset.yml

- name: Import user
  ansible.builtin.import_tasks: user.yml

- name: Import Route53
  ansible.builtin.import_tasks: route53.yml

- name: Include keypair
  when: operation in ['CREATE', 'RESET']
  ansible.builtin.include_tasks: keypair.yml

- name: Include ipa
  when:
  - kerberos_user is defined
  - kerberos_password is defined or kerberos_keytab is defined
  ansible.builtin.include_tasks: ipa.yml

- name: Import pool
  ansible.builtin.import_tasks: pool.yml
