- name: Generate SSH keys
  ansible.builtin.shell: ssh-keygen -b 2048 -t rsa -f /home/{{ ansible_user }}/.ssh/id_rsa -q -N ""
  args:
    creates: /home/{{ ansible_user }}/.ssh/id_rsa

- name: Generate SSH pub key
  ansible.builtin.shell: ssh-keygen -y -f /home/{{ ansible_user }}/.ssh/id_rsa > /home/{{ ansible_user }}/.ssh/id_rsa.pub
  args:
    creates: /home/{{ ansible_user }}/.ssh/id_rsa.pub

- name: Slurp public key
  ansible.builtin.slurp:
    path: /home/{{ ansible_user }}/.ssh/id_rsa.pub
  register: idrsapub

- name: Create cluster directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/{{ cluster_name }}
    state: directory
    mode: "0775"

- name: Generate config install-config.yaml
  ansible.builtin.template:
    src: "{{ 'templates/install-config.yaml.j2' }}"
    dest: /home/{{ ansible_user }}/{{ cluster_name }}/install-config.yaml
    owner: "{{ ansible_user }}"
    mode: "0660"

- name: Make a copy of the cluster install config
  ansible.builtin.copy:
    remote_src: true
    src: /home/{{ ansible_user }}/{{ cluster_name }}/install-config.yaml
    dest: /home/{{ ansible_user }}/{{ cluster_name }}/install-config.yaml.bak
    owner: "{{ ansible_user }}"
    mode: "0660"
