---
# This downloads all the extra manifests which are maintained by Tigera
- name: Make sure manifests dir exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/{{ cluster_name }}/manifests/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: ug=rwx,o=rx

- name: Download Project Calico Manifest archive file to home dir
  ansible.builtin.get_url:
    url: https://projectcalico.docs.tigera.io/manifests/ocp.tgz
    dest: "/home/{{ ansible_user }}/"
    validate_certs: false
    mode: ug=rw,o=r
  retries: 3
  delay: 3
  register: r_result
  until: r_result is not failed

# Can't use unarchive module as it does not handle .gz files that do not contain a .tar archive.
- name: Extract Project Calico manifest files
  ansible.builtin.shell:
    cmd: "gtar -x -f /home/{{ ansible_user }}/ocp.tgz --strip-components 1 -C /home/{{ ansible_user }}/{{ cluster_name }}/manifests/"

- name: Verify permissions on Calico manifest files are set
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/{{ cluster_name }}/manifests/"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: ug=rwx,o=rx

- name: Remove downloaded file
  ansible.builtin.file:
    state: absent
    path: "/home/{{ ansible_user }}/ocp.tgz"
