---
- name: Get the list of installed collections (EE)
  ansible.builtin.command: >-
    ansible-galaxy collection list --format json
  register: r_installed_collections

- name: Create temporary file for requirements.yml (EE)
  ansible.builtin.tempfile:
    state: file
    suffix: requirements
  register: r_tempfile

- name: Rewrite requirements, filter out installed collections (EE)
  vars:
    installed_collections: >-
      {{ r_installed_collections.stdout | from_json }}
  ansible.builtin.copy:
    dest: "{{ r_tempfile.path }}"
    content: >-
      {{ r_requirements_content
      | agnosticd_filter_out_installed_collections(installed_collections)
      | to_yaml }}
    mode: "0664"

- name: Install collections from requirements.yml (EE)
  vars:
    __collections_path: "{{ lookup('config', 'COLLECTIONS_PATHS')[0] }}"
  ansible.builtin.command: >-
    ansible-galaxy collection install
    -r "{{ r_tempfile.path }}"
    -p "{{ __collections_path | quote }}"
    --force-with-deps
  register: r_ee_ansible_galaxy_install_collections
  until: r_ee_ansible_galaxy_install_collections is successful
  retries: 10
  delay: 30

- name: Cleanup tempfile (EE)
  ansible.builtin.file:
    path: "{{ r_tempfile.path }}"
    state: absent
