---
- name: Step 0000 Setup Output Directory
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Set output_dir if not defined
    when: output_dir is not defined
    ansible.builtin.set_fact:
      output_dir: '/tmp/output_dir'

  - name: Create output_dir if it does not exists
    ansible.builtin.file:
      path: "{{ output_dir }}"
      state: directory
      mode: "0775"

  - name: Attempt to restore output_dir contents
    when: agnosticd_save_output_dir_archive is defined
    ansible.builtin.include_role:
      name: agnosticd_restore_output_dir

  - name: Touch file provision-user-data.yaml and provision-user-info.yaml
    ansible.builtin.file:
      state: touch
      path: "{{ [ output_dir, 'provision-' ~ item ] | path_join }}"
      mode: "0664"
    loop:
    - user-info.yaml
    - user-data.yaml

  - name: Create empty user-info.yaml and user-data.yaml in output dir
    when: not agnosticd_preserve_user_data | default(false) | bool
    ansible.builtin.copy:
      content: |
        ---
      dest: "{{ [ output_dir, ACTION ~ '-' ~ item ] | path_join }}"
      mode: "0664"
    loop:
    - user-info.yaml
    - user-data.yaml

  - name: Create symlink user-data.yaml -> provision-user-data.yaml
    ansible.builtin.file:
      src: "{{ [output_dir, 'provision-' ~ item] | path_join }}"
      dest: "{{ [output_dir, item] | path_join }}"
      state: link
      force: true
    loop:
    - user-info.yaml
    - user-data.yaml
