---
- name: Create the base directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.gcp"
    mode: "0700"
    owner: "{{ ansible_user }}"
    state: directory

- name: Create key file for Google Cloud SDK
  ansible.builtin.copy:
    src: "{{ gcp_credentials_file }}"
    dest: "/home/{{ ansible_user }}/.gcp/osServiceAccount.json"
    mode: "0600"
    owner: "{{ ansible_user }}"
  become: false
