---
# Only Satellite is supported

# Preferred variable name uses role name as prefix with compatibility for older variable names
set_repositories_satellite_ca_rpm_url: "https://{{ set_repositories_satellite_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm"
set_repositories_satellite_activationkey: "{{ satellite_activationkey | default('') }}"
set_repositories_satellite_hostname: "{{ set_repositories_satellite_url | default(satellite_url) | default('') }}"
# pattern matching a pool name for attachment via Satellite
# set_repositories_satellite_pool: "^$"

set_repositories_satellite_force_register: false

# By default use content view mode
set_repositories_use_content_view: true

ACTION: provision
